Feature/license status disabled
drazenbebic/license-manager-for-woocommerce pull request #136
Opened 2020-11-05 11:52 UTC by tony-defa

Hi @drazenbebic 

a new 'disabled' status has been added to the LicenseStatusEnum class. The new status is used for denying activation/deactivation over the API and over the MyAccount license page and can be set over the license list page (admin) from bulk actions. This is beneficial for subscriptions that have been set on-hold or have been cancelled. The status of the license will change automatically if the subscription will be put on-hold or get cancelled. The license status will return to its pevious state, when the subscription is reactivated. The subscription status change can be changed manually or can change if e.g. the renewal order failed.

2020-12-02 14:41 UTC, drazenbebic commented
Hello @tony-defa 

thank you for your great contribution. Sorry I really don't have much time these days to take a look at everything. I'll check it out (hopefully soon) and let you know.

2020-12-05 08:22 UTC, drazenbebic requested changes
Hello @tony-defa 

I've got some minor changes I would like you to make before I merge this into the feature branch.

2020-12-05 08:22 UTC, drazenbebic commented on includes/integrations/woocommerce-subscriptions/Suspend.php
> +            error_log("LMFWC: Skipped because the parent orders could not be found. ");
Please remove all `error_log` function calls, those are only for debugging.

2020-12-05 08:22 UTC, drazenbebic commented on includes/lists/LicensesList.php
> +            'mark_as_disabled'  => __('Mark as disabled', 'license-manager-for-woocommerce'),
Can you please move `mark_as_disabled` below `deactivate` and rename to just `disable`? You will also have to change the slug in the `processBulkActions()` method.

2020-12-05 08:22 UTC, drazenbebic commented on includes/lists/LicensesList.php
> +            case 'mark_as_disabled':
Please change `mark_as_disabled` to `disable` and move below `deactivate`

2020-12-05 14:00 UTC, tony-defa commented
Hi @drazenbebic 

the requested changes are applied.

2020-12-05 14:07 UTC, drazenbebic approved these changes
All is well 💯

2020-12-05 14:07 UTC, merged