Introducing the new product management & order downloads expiration feature
drazenbebic/license-manager-for-woocommerce pull request #143
Opened 2020-12-02 22:53 UTC by Johnny99211

Hi Drazen,

as I wrote in my last PR, I'll now release the new product management feature to you which I developed in the last days because of my personal needs. In the following text I'll explain every change to you and add some examples you can use at your page like API descriptions and documentations. 

Since I've found no translation files, I think I need to translate the plugin a different way. I'm developing WP plugins for 3 years now but I've included all my language files directly into the plugin so please tell me the way you did this so that I can add my translation.

**Initial idea for the new feature**
Since I'm a WordPress developer I wanted to include a licensing system into my WP plugins I've developed. First I had the same idea for a plugin like yours but then I've found your plugin and it nearly fitted my needs. But some things were missing: 

- Automatic expirations of downloads in orders when the corresponding license expires
- A simple way to provide plugin updates to my customers
---
**Automatic expirations of downloads**
---
When a customer buys a digital product that contains downloadable content and he enabled the correct setting in the plugin, the file/files expiration date in an order get's set/changed in the following situations:

- License key generation via API and GUI using `valid_for` or `expires_at`
- License key changes via API and GUI using `valid_for` or `expires_at`

![image](https://user-images.githubusercontent.com/43766368/100937056-b8144c00-34f2-11eb-816a-5c5b75db2ed3.png)

The expiration get's only set when an order is set in the license. I've tested this multiple times without any issues. 

**Product updates via license**
---
When I want to sell a WordPress plugin license for example, I need to be able to provide plugin updates somehow because the plugin is not listed at WordPress directly. So I've created a new setting in the plugin that allows me to enable this feature. When it's enabled, I can see a new section in the WooCommerce product license tab:

![image](https://user-images.githubusercontent.com/43766368/100938587-3d006500-34f5-11eb-8d80-ce2af6f62a4f.png)

This allows me to define some important things about the plugin. The data will be used later in the API request. 
When the license selling checkbox for a product and the product download management checkbox is checked and a product is virtual and downloadable, your plugin only allows one file now in the downloadable files table since this must be a package like .zip for WordPress, otherwise a use of the WordPress update API would not be possible:

![image](https://user-images.githubusercontent.com/43766368/100939006-e5162e00-34f5-11eb-9d54-8f82a61a87df.png)

So for example when I add here the link to my plugin from my secure folder in WordPress and fill out every information, I'm good to go so let's talk about the two new endpoints.

**v2/products/update/{license_key}**
This endpoint can be called now to receive infos about the current installed plugin/product I've sold to my customer. So here is an example call for a license:

> https://www.xxxx.de/wp-json/lmfwc/v2/products/update/XXXX-XXXX-XXXX-XXXX

```
{
    "success": true,
    "data": {
        "license_key": "XXXX-XXXX-XXXX-XXXX",
        "url": "https://www.xxxx.de/shop/plugins/woomex/",
        "new_version": "1.1.0",
        "package": "https://xxxx.xxxx.de/wp-json/lmfwc/v2/products/download/latest/XXXX-XXXX-XXXX-XXXX?consumer_key=ck_............&consumer_secret=cs_..........",
        "tested": "5.5.3",
        "requires": "5.4.0",
        "requires_php": "7.0.0",
        "last_updated": "2020-12-01 23:29:57",
        "sections": {
            "changelog": "<p><strong>1.0.0</strong></p><ul><li>Initial release</li></ul>"
        }
    }
}
```
I can now pass this for example to the WordPress plugins API. WordPress automatically checks now if the installed plugin version is older than the one provided in the response. In the case this is true, WordPress shows an update for my plugin:

![image](https://user-images.githubusercontent.com/43766368/100939643-ec8a0700-34f6-11eb-8b1d-8351fc24686a.png)

When I now click the details button, I can now see the other details:

![image](https://user-images.githubusercontent.com/43766368/100939716-0c212f80-34f7-11eb-900a-b946e70b6db3.png)

But now we need to think about the updating part. Since you can provide WordPress an URL where the upgrader can download the new version from, I've passed another parameter package in the response which points to the second endpoint. The URL get's build together from the current auth params (GET or SERVER) and the license. When I press the update button now, WordPress automatically downloads the new package via the second new endpoint:

**v2/products/download/latest/{license_key}**
So when WordPress wants to download the update package, the endpoint first checks if the license exists and all that stuff you did for the other endpoints too (I've not included an expiration check since this needs to be done on the client side I think).

When everything is ok, the endpoint takes the first and only file from our product downloads table and returns it to WordPress where it will be unpacked and installed.

![image](https://user-images.githubusercontent.com/43766368/100940526-640c6600-34f8-11eb-91e4-7b4ab376c33c.png)

**Commit notices**
---
- Add new product management for e.g. WordPress plugins or themes sold via WooCommerce in combination with a license
- Re-write script.js using jQuery because plain JS was too complex and hacky for the new feature (I can explain you how it works in german if you need)
- Introduce order download expiration when a license key expires (updates when license updates in GUI & API)
- Introduce new endpoint for the products management (/products/update/ & /products/download/latest/)
- Extend Setup.php knowing the the controller
- Extend settings page (two new checkboxes for the new feature)
- Extend license tab in WooCommerce product showing the new input fields for product management
- Small UI fixes (Space between the two license buttons in an order)
![image](https://user-images.githubusercontent.com/43766368/100941053-48558f80-34f9-11eb-9641-310e39fd4260.png)

So I hope you like this new feature. I've tested it multiple times and I can confirm 100% that everything works. I'm also using this since 2 days without any issues. 

The script re-write was also tested 100% successful from my side. I hope you are not mad about the jQuery thing but it was my only solution for the files table changes because this would be a really complex code in plain JS.

If you have any questions, you can write me and I will help you out with coding. I'm working a lot with WooCommerce and WordPress coding so don't be shy to ask.

2020-12-04 22:05 UTC, drazenbebic commented
@Johnny99211 

I'm absolutely loving this feature! You've also pretty much written a "How-To" guide along with it. I just need to test it a bit more myself and then I'll merge it into the develop branch. Will be included in v2.3.0 if all goes well!

Absolutely amazing, well done!

2020-12-05 07:37 UTC, drazenbebic requested changes
I got some minor changes that I would really appreciate if you could work out before I merge into develop.

There is one bigger thing that I would like to ask of you: I noticed that you added the new product options for simple products only. Is there a reason why they are not included for variable products? Could I bother you to do those as well? If you don't want to, it's also fine. I can do that part myself 👍 

Great work you've done here!

2020-12-05 07:37 UTC, drazenbebic commented on includes/api/v2/Products.php
> +			$productDownloadFile = ABSPATH . ltrim( wp_make_link_relative( $product->get_file_download_path( array_key_first( $productDownloads ) ) ), '/' );
`array_key_first()` is a PHP 7.3 method, currently the PHP requirement sits pretty low at PHP 5.6, and this would bump it up significantly. What are your thoughts on rewriting this part? Here is an idea:

https://stackoverflow.com/questions/1028668/get-first-key-in-a-possibly-associative-array

2020-12-05 07:37 UTC, drazenbebic commented on includes/api/v2/Products.php
> +            'last_updated' => $lastUpdated ?? '',
Same thing here. Coalesce operators are PHP 7.0+. I would prefer a more backwards-compatible solution like:

`($lastUpdated ? $lastUpdated : '')`

2020-12-05 07:37 UTC, drazenbebic commented on includes/api/v2/Products.php
> +		$productDownloadFile = ABSPATH . ltrim( wp_make_link_relative( $product->get_file_download_path( array_key_first( $productDownloads ) ) ), '/' );
same as line 159

2020-12-05 07:37 UTC, drazenbebic commented on includes/api/v2/Licenses.php
> +		    $expiresAt = $updateData['expires_at'] ?? License::instance()->validFor2ExpiresAt( $updateData['valid_for'] );
Please avoid PHP 7.0 coalesce operators, as the current PHP requirement sits at 5.6. Changes like these would require a major version bump, as it could break existing installations.

2020-12-05 07:37 UTC, drazenbebic commented on includes/controllers/License.php
> +	public function validFor2ExpiresAt( $validFor )
I think it would be better to move this method to the `/functions/lmfwc-core-functions.php` file. This way, the `License` class wouldn't have to be a Singleton, and other developers could make easier use of the function should they need it.

2020-12-05 07:37 UTC, drazenbebic commented on includes/integrations/woocommerce/Order.php
> +	public function updateOrderDownloadsExpiration( $expiresAt, $orderId )
Same thing as with `validFor2ExpiresAt`. Please move it to the `lmfwc-core-functions.php` file. Easier access for other developers, and this class wouldn't have to be a Singleton anymore.

2020-12-05 07:37 UTC, drazenbebic commented on includes/integrations/woocommerce/Controller.php
> +use WC_Customer_Download;
Unused import, please remove

2020-12-05 07:37 UTC, drazenbebic commented on includes/integrations/woocommerce/Controller.php
> +use WC_Data_Store;
Unused import, please remove

2020-12-05 21:46 UTC, drazenbebic approved these changes

2020-12-05 21:46 UTC, merged

2020-12-07 08:40 UTC, Johnny99211 commented on includes/api/v2/Products.php
> +			$productDownloadFile = ABSPATH . ltrim( wp_make_link_relative( $product->get_file_download_path( array_key_first( $productDownloads ) ) ), '/' );
Hi Drazen, 

I've wrote everything in PHP 7.4 because this is the required version by the latest WordPress:

https://de.wordpress.org/about/requirements/

So sorry for the wrong version.


BG
Johnny

2020-12-07 08:41 UTC, Johnny99211 commented on includes/api/v2/Products.php
> +            'last_updated' => $lastUpdated ?? '',
You don't need to do the unnecessary boxing here. You can just do `$lastUpdated ? $lastUpdated : ''`